name: pgportfolio37
channels:
  - defaults
  - anaconda
  - conda-forge
  - bioconda
  - pytorch
  - r
  - msys2
  - menpo
  - simpleitk
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - absl-py=0.12.0
  - astor=0.8.1
  - blas=1.0
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - coverage=5.5
  - cudatoolkit=10.0.130
  - cudnn=7.6.5=cuda10
  - cupti=10.0.130
  - cvxopt=1.2.0
  - cycler=0.10.0
  - cython=0.29.22
  - dbus=1.13.18
  - expat=2.3.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gast=0.2.2
  - glib=2.68.0
  - glpk=4.65
  - gmp=6.2.1
  - google-pasta=0.2.0
  - grpcio=1.36.1
  - gsl=2.4
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - importlib-metadata=3.7.3
  - intel-openmp=2020.2
  - jpeg=9b
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - metis=5.1.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1k
  - opt_einsum=3.1.0
  - pandas=0.23.4
  - pcre=8.44
  - pillow=8.2.0
  - pip=21.0.1
  - protobuf=3.14.0
  - pympler=0.9
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - python=3.7.10
  - python-dateutil=2.8.1
  - pytz=2021.1
  - qt=5.9.7
  - readline=8.1
  - scipy=1.6.2
  - seaborn=0.11.1
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.35.3
  - suitesparse=5.2.0
  - tbb=2020.3
  - tensorboard=1.15.0
  - tensorflow=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - tensorflow-gpu=1.15.0
  - termcolor=1.1.0
  - tk=8.6.10
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - tflearn==0.5.0
